### ISSUE TITLE
Upgrade composer for react-loop 1.x?

### ISSUE THREAD

**Issue by ptheofan** [clue/php-multicast-react#14]
Any chance of upgrading the composer dependencies to allow using the latest react-loop?

![image](https://user-images.githubusercontent.com/880939/83327201-73290780-a27a-11ea-8452-cd305cc8bf7f.png)

![image](https://user-images.githubusercontent.com/880939/83327209-7b814280-a27a-11ea-9364-cda1317ee23e.png)

**Comment by clue** [comment]
Thanks for reporting, this has already been resolved via #11 and will be available in the next release :shipit: In the meantime you can also use `dev-master`
