### ISSUE TITLE
How send Multicast message to online client?

### ISSUE THREAD

**Issue by uiosun** [clue/php-multicast-react#19]
The local is done, but I want use reactphp-multicast to online game.

can i do it? (client use UDP connect server)

**Comment by clue** [comment]
@Sun-FreePort Excellent question!

You wouldn't usually send a multicast datagram over the public internet (unless you've first set up a tunnel connection that essentially acts like a normal LAN). See also https://networkengineering.stackexchange.com/questions/47994/is-multicast-on-the-public-internet-possible-and-if-yes-how/47995.

In any real-world example, you would most likely want to send unicast datagram over the internet instead.

I hope this helps :+1:

**Comment by uiosun** [comment]
Very useful, thanks for you help!
